"""create initial tables

Revision ID: 12d4f8c2af9f
Revises: 15fc89db2b17
Create Date: 2026-03-21 21:11:34.925038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d4f8c2af9f'
down_revision: Union[str, Sequence[str], None] = '15fc89db2b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('_password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False, comment='邮箱id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱地址'),
    sa.Column('email_code', sa.String(length=255), nullable=False, comment='邮箱验证码'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emails_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emails')),
    sa.UniqueConstraint('email', name=op.f('uq_emails_email'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    op.drop_table('users')
    # ### end Alembic commands ###
